services:
  tablo-legacy-m3u:
    build: .
    ports:
      - 5004:5004
    environment:
      TABLO_IP: "" # Set to skip autodiscovery
      AUTODISCOVER_TABLO: true
      HOST: 0.0.0.0
      PORT: 5004
      LOG_LEVEL: DEBUG
      DEBUG: true
      ENABLE_EPG: true
      CACHE_TTL: 60
    volumes:
      - ./src:/app/src
    restart: unless-stopped
