"""Vite manifest integration for Flask."""

import json

from pathlib import Path
from typing import Any

from flask import Flask, url_for
from markupsafe import Markup


def init_vite(app: Flask) -> None:
    """Register a Jinja2 global that resolves Vite asset paths.

    This reads the Vite manifest file generated by `vite build` to determine the correct
    paths for CSS and JS assets. In development mode, the manifest is reloaded on each
    request to reflect changes without restarting the server.
    """
    dist_dir = Path(app.static_folder or "") / "dist"
    manifest_path = dist_dir / ".vite" / "manifest.json"

    def _load_manifest() -> dict[str, dict[str, Any]]:
        if manifest_path.exists():
            result: dict[str, dict[str, Any]] = json.loads(manifest_path.read_text())
            return result
        return {}

    manifest_cache: dict[str, dict[str, Any]] = _load_manifest()

    def vite_asset(entry: str) -> Markup:
        """Return HTML tags for a Vite entry point's CSS and JS assets."""
        manifest = manifest_cache if not app.debug else _load_manifest()

        chunk = manifest.get(entry)

        if chunk is None:
            return Markup("<!-- vite: {} not found -->").format(entry)

        tags: list[str] = [
            Markup('<link rel="stylesheet" href="{}">').format(
                url_for("static", filename=f"dist/{css_file}")
            )
            for css_file in chunk.get("css", [])
        ]

        js_file = chunk.get("file", "")
        if js_file.endswith(".css"):
            tags.append(
                Markup('<link rel="stylesheet" href="{}">').format(
                    url_for("static", filename=f"dist/{js_file}")
                )
            )
        elif js_file:
            tags.append(
                Markup('<script defer src="{}"></script>').format(
                    url_for("static", filename=f"dist/{js_file}")
                )
            )

        return Markup("\n").join(tags)

    app.jinja_env.globals["vite_asset"] = vite_asset
