# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

permissions:
    contents: read

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
              with:
                  enable-cache: true

            - name: Ruff check
              run: uv run ruff check .

            - name: Ruff format
              run: uv run ruff format --check .

            - name: Djlint
              run: uv run djlint tablo_legacy_m3u/templates/ --lint --check

    typecheck:
        name: Type check
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
              with:
                  enable-cache: true

            - name: mypy
              run: uv run mypy .

    test:
        name: Test
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
              with:
                  enable-cache: true

            - name: Run tests
              run: uv run pytest
