# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Docker Image Test

permissions:
    contents: read

on:
    workflow_dispatch:

    push:
        branches: [main]
        paths:
            - Dockerfile
            - .dockerignore
            - pyproject.toml
            - uv.lock
            - tablo_legacy_m3u/**
    pull_request:
        branches: [main]
        paths:
            - Dockerfile
            - .dockerignore
            - pyproject.toml
            - uv.lock
            - tablo_legacy_m3u/**

jobs:
    test_docker_container:
        name: Build and Test Docker image

        runs-on: ubuntu-24.04

        steps:
            - name: Checkout Code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

            - name: Build Image
              uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
              with:
                  context: .
                  load: true
                  tags: tablo-legacy-m3u
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Smoke Test
              run: |
                  docker run --rm tablo-legacy-m3u \
                    python -c "from tablo_legacy_m3u import app; print(app.name)"
